### ISSUE TITLE
NoneType in vanilla_mask_3d

### ISSUE THREAD

**Issue by poperian** [PAIR-code/saliency#12]
Hi,
I would like to create the saliency map for a DNN that I use for classification of 4 types of images. I manage to calculate the gradient_saliency but when I try to calculate any of the masks e.g vanilla_mask_3d I get the following error: 

`vanilla_mask_3d = gradient_saliency.GetMask(im, feed_dict = {neuron_selector: prediction_class})
Traceback (most recent call last):`
`File "<ipython-input-19-7508dfaae246>", line 1, in <module>
    vanilla_mask_3d = gradient_saliency.GetMask(im, feed_dict = {neuron_selector: prediction_class})`

  `File "/usr/local/lib/python2.7/dist-packages/saliency/base.py", line 97, in GetMask
    return self.session.run(self.gradients_node, feed_dict=feed_dict)[0]`

   `File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 889, in run
    run_metadata_ptr)`

   `File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1105, in _run
    self._graph, fetches, feed_dict_tensor, feed_handles=feed_handles)`

  `File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 414, in __init__
    self._fetch_mapper = _FetchMapper.for_fetch(fetches)`

  `File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 231, in for_fetch
    (fetch, type(fetch)))`

`TypeError: Fetch argument None has invalid type <type NoneType'>`

Could you please tell me where might this error be coming from since I don't seem to have a NoneType argument in my prediction_class.

Cheers,
Pouyan

**Comment by poperian** [comment]
I managed to solve it in case anyone had the same problem. The error was coming from tf.gradients() function which was returning "None" due to mishandling the tensors which were built upon in the graph.

**Comment by yashkotadia** [comment]
Could you please elaborate on how you solved the problem? I've spent hours trying to find a solution.

**Comment by poperian** [comment]
The problem comes from the fact that the correct tensor is not being passed to the  tf.gradients()  function. In my case I was not passing the tensor with the softmax layer which calculate the prediction to the function:
 `gradient_saliency` = saliency.GradientSaliency(graph, sess, y, `images))`. 
Therefore the gradient ended up being None.

**Comment by remindchobits** [comment]
> The problem comes from the fact that the correct tensor is not being passed to the tf.gradients() function. In my case I was not passing the tensor with the softmax layer which calculate the prediction to the function:
> `gradient_saliency` = saliency.GradientSaliency(graph, sess, y, `images))`.
> Therefore the gradient ended up being None.

Hello, have you solved this problem? I met the same problem but have no idea what's wrong. the y? I noticed that tensor y has no shape
