### ISSUE TITLE
What about tensorflow 2.0

### ISSUE THREAD

**Issue by doantientai** [PAIR-code/saliency#16]
I am trying to apply saliency to a model created with tensorflow 2.0 with the built-in keras. As we don't have session in TF2.0. Where should I start?

**Comment by nishanthta** [comment]
I'm facing the same problem. Were you able to find a solution?
My idea was to try and restore the graph and make modifications there but that doesn't seem to be working out

**Comment by doantientai** [comment]
You may check this out:
https://github.com/sicara/tf-explain
