### ISSUE TITLE
RuntimeWarning: Invalid value encountered in percentile

### ISSUE THREAD

**Issue by resonance20** [PAIR-code/saliency#19]
I have the following problem when attempting to calculate vanilla gradients:

`C:\Users\z003zv1a\AppData\Roaming\Python\Python36\site-packages\numpy\lib\function_base.py:3652: RuntimeWarning: Invalid value encountered in percentile
  interpolation=interpolation)
C:\Users\z003zv1a\AppData\Roaming\Python\Python36\site-packages\numpy\core\fromnumeric.py:83: RuntimeWarning: invalid value encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\image.py:405: UserWarning: Warning: converting a masked element to nan.
  dv = (np.float64(self.norm.vmax) -
C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\image.py:406: UserWarning: Warning: converting a masked element to nan.
  np.float64(self.norm.vmin))
C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\image.py:412: UserWarning: Warning: converting a masked element to nan.
  a_min = np.float64(newmin)
C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\image.py:417: UserWarning: Warning: converting a masked element to nan.
  a_max = np.float64(newmax)
C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\colors.py:916: UserWarning: Warning: converting a masked element to nan.
  dtype = np.min_scalar_type(value)
C:\Users\z003zv1a\AppData\Roaming\Python\Python36\site-packages\numpy\ma\core.py:718: UserWarning: Warning: converting a masked element to nan.
  data = np.array(a, copy=False, subok=subok)`

**Comment by bwedin** [comment]
Is this still an active issue? We've added some additional error messages in https://github.com/PAIR-code/saliency/pull/49, so you may see some more informative error messages there. If the error message is the same, please add the full code you're running and the line that you encounter the error (i.e. is it while running getMask or earlier/later).

This is a pretty old issue so I'm closing for now, but feel free to reopen. Thanks!
