### ISSUE TITLE
Use saliency code for other checkpoints

### ISSUE THREAD

**Issue by sofnom** [PAIR-code/saliency#38]
Dear authors, 

Thank you for the comprehensive code examples!
I would like to modify your code to use my own Inception v3 checkpoints. However, when I save the checkpoints in tensorflow I get three files (.meta, .graph and .index) instead of one .ckpt file and I was wondering if you could help me modify your example code accordingly to do so.

Thank you!

**Comment by bwedin** [comment]
For trying to use a TF1 checkpoint, these links may be of use: 
https://www.tensorflow.org/api_docs/python/tf/compat/v1/saved_model/loader
https://stackoverflow.com/questions/41265035/tensorflow-why-there-are-3-files-after-saving-the-model
The short answer is that those extra files are expected and should help you load your own checkpoint.

With https://github.com/PAIR-code/saliency/pull/49, you should be able to store your model in any way you like, as long as you can return gradients given an input, which should work with inception models stored in TF1 as well as other frameworks. Let us know if you have other questions!
