### ISSUE TITLE
module 'saliency.core' has no attribute 'GuidedIG'

### ISSUE THREAD

**Issue by zhixiongzh** [PAIR-code/saliency#65]
Hi,
I am running the Example_pytorch.ipynb in the branch pytorch-notebook.
When I run the cell of Guided IG, the error is shown,
`module 'saliency.core' has no attribute 'GuidedIG'`

How to solve this? Thanks for any suggestion.

**Comment by zhixiongzh** [comment]
I realize I didn't download all the codes in the branch, just pip install saliency, which haven't been updated to the test version.

**Comment by tolga-b** [comment]
Hi zhixiongzh we just updated the pip version to 0.1.3, you should be able to just pip install now!
Thanks for reporting this.

**Comment by zhixiongzh** [comment]
> Hi zhixiongzh we just updated the pip version to 0.1.3, you should be able to just pip install now!
> Thanks for reporting this.

Great! That helps a lot. Thanks for your effort.
