### ISSUE TITLE
why divide by 255 in the LoadImage function

### ISSUE THREAD

**Issue by hzhz2020** [PAIR-code/saliency#66]
Dear Authors

This is a very cool repo. I am trying to use it with my own checkpoint and images. 
I look at your Examples_tf1.ipynb, the **LoadImage** function divide the image values by 255. I'm wondering why divide by 255, is it because when training the inception checkpoint, the input image is divided by 255?

**Comment by bwedin** [comment]
That's correct, the model is trained on images where all pixels are scaled to the range [0,1].
