### ISSUE TITLE
pip install saliency will always install a cpu version of tensorflow

### ISSUE THREAD

**Issue by MugleLei** [PAIR-code/saliency#9]
![image](https://user-images.githubusercontent.com/30332538/40214610-50e81f66-5a8e-11e8-8ac2-cddd79950608.png)
While I already have installed a gpu version of tensorflow(the pic above), 'pip install saliency' will still install a cpu version of tensorflow for me(the pic below), is there any way to avoid this? or is two version of tensorflow exist simultaneously not a problem
![image](https://user-images.githubusercontent.com/30332538/40214603-456c3424-5a8e-11e8-946f-5ef4ccc90f4b.png)

**Comment by bwedin** [comment]
https://github.com/PAIR-code/saliency/pull/49 moves tensorflow into the subpackage tf1, so pip install should not add an installation of tensorflow. Additionally, versions past TensorFlow v2.0 does not make the distinction between the two versions.
